### ISSUE TITLE
BMA variables problems

### ISSUE THREAD

**Issue by Sikys11235** [PetrCala/Diploma-Thesis#38]
Hi Petr,
When I try to run BMA with many variables (>60) I obtain an error.
Seems like an indentation error as the problem happens only after certain number of variables included in the BMA model (i.e., value TRUE in the bma column in var_list, problem is at around 60 variables). Less variables (around 40) is ok. As a very lazy debug, I tried to shorten the variables description but the problem persisted.

Problem: 

Error in str2lang(x) : <text>:1:882: unexpected symbol
1: phics_control + temperature_control + stock_control + fuels_control + income_control + reduced_form + structural_form + dynamic_model + static_model + RE + FE + VAR + ARDL + ECM + VECM + DS + 

(debug location in the next window)
function (s) 
.Internal(str2lang(s))

s is the string of all the variables that should be included in the BMA "effect ~ se + ...[other variables]", as can be seen below:
<img width="428" alt="Snímek obrazovky 2024-02-20 v 18 21 24" src="https://github.com/PetrCala/Diploma-Thesis/assets/125301922/4635f9c4-0040-4182-9aff-b3e0647548fb">

Was not able to figure out the reason for the issue in the source nor how to modify the s string. So just a heads up (not prio - did part of it manually).

Best,
V

**Comment by PetrCala** [comment]
Howdie, my hunch for why this may happen is invalid characters in one (or more) of the variable names, given the `Unexpected symbol` error.

First, I suggest you check that none of the variables contain invalid characters, like spaces, diacritics, etc. Maybe numbers are a problem? Pretty sure this error happens during the conversion of the variables to a long string, which is a process that should not fail with the length of the input. However, you can check that too, by invoking the `str2lang` with a really long string. The variable names themselves seem okay from just the picture, but I'd still guess the issue could be there. 

Maybe it is a good idea to run the call with the same number of variables, but different names, so that you can verify whether the error is really not just in naming. If the function still fails, then yeah, length might be the issue.

If you have any more context for the error, that could help pinpoint the issue, I'd be glad to take a look. Thanks for the heads up again

**Comment by Sikys11235** [comment]
Hi Petr,

so now I finally had courage to face this issue again. You are right, seems like the problem was indeed with my variable 2SLS, apparently having a number for variable is not allowed. Excuse my profound stupidity.

Best,
VS
